org: hrz88
service: pewh

frameworkVersion: ^4.4.13
configValidationMode: error

provider:
  name: aws
  runtime: provided.al2
  architecture: arm64
  stage: ${opt:stage, 'local'}
  region: ${opt:region, 'us-east-1'}

custom:
  stage: ${opt:stage, 'local'}
  localstack:
    debug: true
    stages:
      - local
    host: http://localhost
    edgePort: 4566
    lambda:
      mountCode: false

plugins:
  - serverless-localstack

package:
  individually: true

functions:
  restapi:
    handler: bootstrap
    package:
      artifact: bin/restapi.zip
    events:
    - http:
        method: get
        path: /api/v1/rooms
        cors:
          origin: '*'
    - http:
        method: get
        path: /api/v1/rooms/another
        cors:
          origin: '*'
  bookingCreated:
    handler: bootstrap
    package:
      artifact: bin/bookingCreated.zip
    events:
      - sns:
          arn: !Ref BookingCreated
          topicName: booking-created-${sls:stage}
  bookingPaid:
    handler: bootstrap
    package:
      artifact: bin/bookingPaid.zip
    events:
      - sns:
          arn: !Ref BookingPaid
          topicName: booking-paid-${sls:stage}

resources:
  Resources:
    BookingCreated:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: 'Booking Created'
        TopicName: booking-created-${sls:stage}
    BookingPaid:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: 'Booking Paid'
        TopicName: booking-paid-${sls:stage}
